#! /bin/sh

cd /zd1/rbn

# download any new RBN zip files
download-rbn

# convert to one big file, rbndata.tmp, adding friendly date and epoch data to each line
convert-rbn

# RBN data are not always in chronological order; no need to perform a stable (i.e., -s) sort
#nice sort -t , --temporary-directory=/zfs1/tmp --key=15 -n rbndata.tmp > rbndata.csv

#rm rbndata.tmp

# 200114
nice sort -t , --temporary-directory=/tmp --key=15 -n -o rbndata.tmp rbndata.tmp

rsync --inplace --no-whole-file rbndata.tmp rbndata.csv
rm rbndata.tmp
