#! /bin/sh

cd /zd1/rbn

# download any new RBN zip files
download-rbn

# convert to one big file, rbndata.tmp, adding friendly date and epoch data to each line
convert-rbn

# RBN data are not always in chronological order; no need to perform a stable (i.e., -s) sort
#nice sort -t , --temporary-directory=/zfs1/tmp --key=15 -n rbndata.tmp > rbndata.csv

#rm rbndata.tmp

# 210409 remove duplicate lines
#nice sort --temporary-directory=/tmp rbndata.tmp | uniq > rbndata1.tmp

# 200114
#nice sort -t , --temporary-directory=/tmp --key=15 -n -o rbndata1.tmp rbndata1.tmp

nice sort --temporary-directory=/tmp rbndata.tmp | nice uniq | nice sort -t , --temporary-directory=/tmp --key=15 -n -o rbndata1.tmp

rm rbndata.tmp

nice rsync --inplace --no-whole-file rbndata1.tmp rbndata.csv
rm rbndata1.tmp

