#! /bin/sh

# program to be used to view the output file
export VIEWER=gwenview

export call=$1
export start_date=$2
export end_date=$3

# replace slashes with hyphens for UNIX-safe versions of the call
export safe_call=`echo -n $call | sed 's/\//-/g'`

plot-sig-zones-9.R $safe_call $start_date $end_date

export filename="$safe_call-$start_date-$end_date-by-zone-9.png"

if [ -s "$filename" ]
   then
     $VIEWER "$filename"
fi
